function [ feature ] = initializeFeature

% use defaults here to get user set up with feature structure
feature = struct(...
    'FEATURE_COLLECTION',   'sample:CONUS_States',...
    'ATTRIBUTE',            'STATE',...
    'GML',                  'CONUS_States.906');

